function buildMultiPointSrcsAzmDistrData()

startTwoEars('tt_general.config.xml');

% pipeline creation
pipe = TwoEarsIdTrainPipe( 'cacheSystemDir', [getMFilePath() '/../../idPipeCache'] );
pipe.featureCreator = FeatureCreators.FeatureSet5Blockmean();
azmLabeler = LabelCreators.IdAzmDistributionLabeler( 'angularResolution', 10, ...
                 'types', {{'speech'},{'knock'},{'keys'},{'switch'}, {'clearthroat'}});
pipe.labelCreator = azmLabeler;
pipe.modelCreator = ModelTrainers.LoadModelNoopTrainer( 'noop' );
pipe.modelCreator.verbose( 'on' );

% data setup
pipe.setData( {'DCASE13_mini_TrainSet_f1.flist',...
               'DCASE13_mini_TrainSet_f2.flist',...
               'DCASE13_mini_TrainSet_f3.flist',...
               'DCASE13_mini_TrainSet_f4.flist',...
               'DCASE13_mini_TestSet.flist'} );
pipe.trainsetShare = 1;
pipe.setupData();

% scene setup
sc(1) = SceneConfig.SceneConfiguration();
sc(1).addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( 'pipeInput' ),...
        'azimuth', SceneConfig.ValGen( 'manual', 90 ) ) );
sc(1).addSource( SceneConfig.PointSource( ...
        'azimuth',SceneConfig.ValGen( 'manual', -90 ),...
        'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
        'loop', 'randomSeq' );
sc(1).addSource( SceneConfig.PointSource( ...
        'azimuth',SceneConfig.ValGen( 'manual', -45 ),...
        'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
        'loop', 'randomSeq' );
sc(1).addSource( SceneConfig.PointSource( ...
        'azimuth',SceneConfig.ValGen( 'manual', -0 ),...
        'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
        'loop', 'randomSeq' );
sc.setLengthRef( 'source', 1, 'min', 15 );
pipe.init( sc, 'fs', 16000 );

% pipeline run
modelPath = pipe.pipeline.run( 'modelPath', 'test_buildMultiPointSrcsAzmDistrData', 'runOption', 'dataStoreUni' );
fprintf( ' -- Data is saved at %s -- \n\n', modelPath );
