function trainAndTestMultiSourceBabyVsAll()

addPathsIfNotIncluded( cleanPathFromRelativeRefs( [pwd '/..'] ) ); 
startIdentificationTraining();

pipe = TwoEarsIdTrainPipe( 'soundDbBaseDir', ...
                           fullfile( xml.dbPath, 'sound_databases', 'generalSoundsNI' ) );
pipe.blockCreator = BlockCreators.DistractedBlockCreator( 1.0, 0.4, ...
                                                          'distractorSources', [2 3],...
                                                          'rejectEnergyThreshold', -30 );
pipe.featureCreator = featureCreators.FeatureSet1Blockmean();
pipe.labelCreator(1) = LabelCreators.BinaryEventTypeLabeler( 'posOutType', 'baby', ...
                                                             'labelBlockSize_s', 1.0 );
pipe.modelCreator = modelTrainers.GlmNetLambdaSelectTrainer( ...
    'performanceMeasure', @performanceMeasures.BAC2, ...
    'cvFolds', 4, ...
    'alpha', 0.99 );
pipe.modelCreator.verbose( 'on' );

pipe.trainset = 'testFlists/NIGENS_trainSet_miniMini.flist';
pipe.setupData();

sc = sceneConfig.SceneConfiguration();
sc.addSource( sceneConfig.PointSource( ...
        'data', sceneConfig.FileListValGen( pipe.pipeline.trainSet(:,:,'wavFileName'), 'all' ),...
        'normalize', true,...
        'loop', 'none' ),...
    'snr', sceneConfig.ValGen( 'manual', 0 ),...
    'snrRef', 1 );
sc.addSource( sceneConfig.PointSource( ...
        'data', sceneConfig.FileListValGen( pipe.pipeline.trainSet('fire',:,'wavFileName'), 'one' ),...
        'normalize', true,...
        'loop', 'randomSeq' ),...
    'snr', sceneConfig.ValGen( 'manual', 0 ),...
    'snrRef', 1 );
sc.addSource( sceneConfig.PointSource( ...
        'data', sceneConfig.FileListValGen( pipe.pipeline.trainSet('general',:,'wavFileName'), 'one' ),...
        'normalize', true,...
        'loop', 'randomSeq' ),...
    'snr', sceneConfig.ValGen( 'manual', 10 ),...
    'snrRef', 1 );
sc.setLengthRef( 'source', 1 );
pipe.init( sc );

modelPath = pipe.pipeline.run( 0 );

fprintf( ' -- Model is saved at %s -- \n\n', modelPath );

% TODO: test