function trainAndTest_BRIR( classname )

if nargin < 1, classname = 'baby'; end;

addPathsIfNotIncluded( cleanPathFromRelativeRefs( [pwd '/..'] ) ); 
startIdentificationTraining();

brirs = { ...
    'impulse_responses/twoears_kemar_adream/TWOEARS_KEMAR_ADREAM_pos1.sofa'; ...
    'impulse_responses/twoears_kemar_adream/TWOEARS_KEMAR_ADREAM_pos2.sofa'; ...
    'impulse_responses/twoears_kemar_adream/TWOEARS_KEMAR_ADREAM_pos3.sofa'; ...
    'impulse_responses/twoears_kemar_adream/TWOEARS_KEMAR_ADREAM_pos4.sofa'; ...
    };


pipe = TwoEarsIdTrainPipe();
pipe.featureCreator = FeatureCreators.FeatureSetRmAmsBlockmean();
% <classname> will be 1, rest -1
oneVsRestLabeler = ... 
    LabelCreators.MultiEventTypeLabeler( 'types', {{classname}}, 'negOut', 'rest' );
pipe.labelCreator = oneVsRestLabeler;
pipe.modelCreator = ModelTrainers.GlmNetLambdaSelectTrainer( ...
    'performanceMeasure', @PerformanceMeasures.BAC2, ...
    'cvFolds', 4, ...
    'alpha', 0.99 );
pipe.modelCreator.verbose( 'on' );

pipe.trainset = 'learned_models/IdentityKS/trainTestSets/NIGENS160807_mini_TrainSet_1.flist';
pipe.testset = [];
pipe.setupData();

sc = SceneConfig.SceneConfiguration();
sc.addSource( SceneConfig.BRIRsource( ...
        brirs{1}, 'speakerId', 1, 'data', SceneConfig.FileListValGen( 'pipeInput' ) )...
    );
sc.addSource( SceneConfig.BRIRsource( brirs{1}, 'speakerId', 2, ...
        'data', SceneConfig.FileListValGen( ...
            pipe.pipeline.trainSet('fileLabel',{{'type',{'general'}}},'fileName') ),...
        'offset', SceneConfig.ValGen( 'manual', 0 )...
     ),...
    'snr', SceneConfig.ValGen( 'manual', 0 ),...
    'loop', 'randomSeq' );
sc.setBRIRheadOrientation( 0.4 ); % point of recorded azm range (0..1)
pipe.init( sc, 'hrir', [] ); % empty hrir to avoid usage of default HRIR

modelPath = pipe.pipeline.run( 'modelName', classname, 'modelPath', 'test_brir' );


pipe = TwoEarsIdTrainPipe();
pipe.featureCreator = FeatureCreators.FeatureSetRmAmsBlockmean();
% <classname> will be 1, rest -1
oneVsRestLabeler = ... 
    LabelCreators.MultiEventTypeLabeler( 'types', {{classname}}, 'negOut', 'rest' );
pipe.labelCreator = oneVsRestLabeler;
pipe.modelCreator = ...
    ModelTrainers.LoadModelNoopTrainer( ...
        fullfile( modelPath, [classname '.model.mat'] ), ...
        'performanceMeasure', @PerformanceMeasures.BAC,...
        'maxDataSize', inf ...
        );


pipe.trainset = [];
pipe.testset = 'learned_models/IdentityKS/trainTestSets/NIGENS160807_mini_TestSet_1.flist';
pipe.setupData();

sc = SceneConfig.SceneConfiguration();
sc.addSource( SceneConfig.BRIRsource( ...
        brirs{1}, 'speakerId', 1, 'data', SceneConfig.FileListValGen( 'pipeInput' ) )...
    );
sc.addSource( SceneConfig.BRIRsource( brirs{1}, 'speakerId', 2, ...
        'data', SceneConfig.FileListValGen( ...
            pipe.pipeline.testSet('fileLabel',{{'type',{'general'}}},'fileName') ),...
        'offset', SceneConfig.ValGen( 'manual', 0 )...
     ),...
    'snr', SceneConfig.ValGen( 'manual', 0 ),...
    'loop', 'randomSeq' );
sc.setBRIRheadOrientation( 0.4 ); % point of recorded azm range (0..1)
pipe.init( sc, 'hrir', [] ); % empty hrir to avoid usage of default HRIR

modelPath1 = pipe.pipeline.run( 'modelName', classname, 'modelPath', 'test_brir' );

fprintf( ' Testing -- Saved at %s -- \n\n', modelPath1 );
