function trainAndTestSegmented()

addPathsIfNotIncluded( cleanPathFromRelativeRefs( [pwd '/..'] ) ); 
startIdentificationTraining();

pipe = TwoEarsIdTrainPipe();
pipe.blockCreator = BlockCreators.DistractedBlockCreator( 1.0, 0.4, ...
                                                          'distractorSources', 2,...
                                                          'rejectEnergyThreshold', -30 );
pipe.ksWrapper = DataProcs.SegmentKsWrapper( 4, 'DemoKS' );
pipe.featureCreator = FeatureCreators.FeatureSet1Blockmean();
babyLabeler = LabelCreators.BinaryEventTypeLabeler( 'posOutType', {'baby'} );
pipe.labelCreator = babyLabeler;
pipe.modelCreator = ModelTrainers.GlmNetLambdaSelectTrainer( ...
    'performanceMeasure', @PerformanceMeasures.BAC2, ...
    'cvFolds', 4, ...
    'alpha', 0.99 );
pipe.modelCreator.verbose( 'on' );

pipe.trainset = 'testFlists/NIGENS_trainSet_miniMini.flist';
pipe.setupData();

sc = SceneConfig.SceneConfiguration();
sc.addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( pipe.pipeline.trainSet(:,:,'wavFileName'), 'all' ),...
        'normalize', true,...
        'loop', 'none' ),...
    'snr', SceneConfig.ValGen( 'manual', 0 ),...
    'snrRef', 1 );
sc.addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( pipe.pipeline.trainSet('fire',:,'wavFileName'), 'one' ),...
        'normalize', true,...
        'loop', 'randomSeq' ),...
    'snr', SceneConfig.ValGen( 'manual', 0 ),...
    'snrRef', 1 );
sc.setLengthRef( 'source', 1 );
pipe.init( sc );

modelPath = pipe.pipeline.run( 'segmentedModel.baby' );

fprintf( ' -- Model is saved at %s -- \n\n', modelPath );

% TODO: test