function trainAndTestMultitarget()

addPathsIfNotIncluded( cleanPathFromRelativeRefs( [pwd '/..'] ) ); 
startAMLTTP();

pipe = TwoEarsIdTrainPipe();
pipe.featureCreator = FeatureCreators.FeatureSet1Blockmean();
% baby will be 1, rest -1
babyVsRestLabeler = ... 
    LabelCreators.MultiEventTypeLabeler( 'types', {{'baby'}}, 'negOut', 'rest' );
% female/male scream will be 1, rest -1
screamVsRestLabeler = ... 
    LabelCreators.MultiEventTypeLabeler( 'types', {{'femaleScream','maleScream'}}, ...
                                         'negOut', 'rest' );
pipe.labelCreator = LabelCreators.MultiLabeler( {babyVsRestLabeler, screamVsRestLabeler} );
pipe.modelCreator = ModelTrainers.GlmNetLambdaSelectTrainer( ...
    'performanceMeasure', @PerformanceMeasures.BAC2, ...
    'cvFolds', 4, ...
    'alpha', 0.99 );
pipe.modelCreator.verbose( 'on' );

pipe.trainset = 'learned_models/IdentityKS/trainTestSets/NIGENS160807_mini_TrainSet_1.flist';
pipe.setupData();

sc = SceneConfig.SceneConfiguration();
sc.addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( 'pipeInput' )  )  );
sc.addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( pipe.pipeline.trainSet(:,'fileName') ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
    'snr', SceneConfig.ValGen( 'manual', 0 ),...
    'loop', 'randomSeq' );
sc.setLengthRef( 'source', 1, 'min', 30 );
pipe.init( sc );

modelPath = pipe.pipeline.run( 'modelName', 'multitarget', 'modelPath', 'test_multitarget' );

fprintf( ' -- Model is saved at %s -- \n', modelPath );


pipe = TwoEarsIdTrainPipe();
pipe.featureCreator = FeatureCreators.FeatureSet1Blockmean();
% baby will be 1, rest -1
babyVsRestLabeler = ... 
    LabelCreators.MultiEventTypeLabeler( 'types', {{'baby'}}, 'negOut', 'rest' );
% female/male scream will be 1, rest -1
screamVsRestLabeler = ... 
    LabelCreators.MultiEventTypeLabeler( 'types', {{'femaleScream','maleScream'}}, ...
                                         'negOut', 'rest' );
pipe.labelCreator = LabelCreators.MultiLabeler( {babyVsRestLabeler, screamVsRestLabeler} );
pipe.modelCreator = ...
    ModelTrainers.LoadModelNoopTrainer( ...
        fullfile( modelPath, 'multitarget.model.mat' ), ...
        'performanceMeasure', @PerformanceMeasures.BAC,...
        'maxDataSize', inf ...
        );

pipe.trainset = [];
pipe.testset = 'learned_models/IdentityKS/trainTestSets/NIGENS160807_mini_TestSet_1.flist';
pipe.setupData();

sc = SceneConfig.SceneConfiguration();
sc.addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( 'pipeInput' )  )  );
sc.addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( pipe.pipeline.testSet(:,'fileName') ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
    'snr', SceneConfig.ValGen( 'manual', 0 ),...
    'loop', 'randomSeq' );
sc.setLengthRef( 'source', 1, 'min', 30 );
pipe.init( sc );

modelPath = pipe.pipeline.run( 'modelName', 'multitarget', 'modelPath', 'test_multitarget' );

fprintf( ' -- Model is saved at %s -- \n', modelPath );


