clearAllButBreakpoints;

startTwoEars( '../../src/identificationTraining/identTraining_repos.xml' );

featureCreator = FeatureCreators.FeatureSet1Blockmean();

% modelCreator = ModelTrainers.BGMMmodelSelectTrainer( ...
%     'performanceMeasure', @PerformanceMeasures.BAC2,...
%     'thr', [.7 .8 .9],...
%     'nComp',[1]);
% % higher values of thr result in using more feature dimensions
% % set thr to 1 if intend to not use feature selection
% % number of components is usually set to a large value, and the model
% % automatically prune out unncecessary components.

% modelCreator = ModelTrainers.MFAmodelSelectTrainer( ...
%     'performanceMeasure', @PerformanceMeasures.BAC2,...
%     'nDim', [2:4],...
%     'nComp', [1:3]);
% % nDim is the local dimensionality of each factor
% % nComp is the number of analyseres
% % in some cases simpler models are preferable as they extract those feature
% % which are more robust to noise and interfernce.

% modelCreator = ModelTrainers.BMFATrainer( ...
%     'performanceMeasure', @PerformanceMeasures.BAC2, ...
%     'nComp', 1 );
% % only need to set nComp to a relatively large value.
% % larger values of nComp bviousely increases computational complexity.
% % too small value of nComp lead to underfitting

% modelCreator = ModelTrainers.vMFTrainer( ...
%     'performanceMeasure', @PerformanceMeasures.BAC2, ...
%     'nComp', 5, ...
%     'thr',1 );

modelCreator = ModelTrainers.GMMmodelSelectTrainer( ...
    'performanceMeasure', @PerformanceMeasures.BAC2,...
    'thr', [.7:.05:.95],...
    'nComp',(2:2:8));

% modelCreator = ModelTrainers.MBFTrainer( ...
%     'performanceMeasure', @PerformanceMeasures.BAC2, ...
%     'nComp', 5 );

% modelCreator = ModelTrainers.MBFmodelSelectTrainer( ...
%     'performanceMeasure', @PerformanceMeasures.BAC2,...
%     'thr', [1],...
%     'nComp',[ 4]);


modelPath = idtrainClean( 'baby', 'trainTestSets/trainSet_miniMini1.flist', ...
    featureCreator, modelCreator );
idtestClean( 'baby', 'trainTestSets/testSet_miniMini1.flist', modelPath );

fprintf( ' -- Model is saved at %s -- \n', modelPath );
