function trainNumSrc(useCaffe,modelNameIdent)

%% inits

addPathsIfNotIncluded( cleanPathFromRelativeRefs( [pwd '/..'] ) );
startIdentificationTraining();
if nargin < 1, useCaffe = false; end
if useCaffe
    addpath('/home/kashefy/sabik/src/caffe/matlab/');
end
if nargin < 2
    modelNameIdent = '';
end
modelPath = 'numSrc';
modelName = [modelPath modelNameIdent];

%% setup pipeline for training

pipe = TwoEarsIdTrainPipe();
% blackboard system knowledge source wrapper for azimut distribution
pipe.ksWrapper = DataProcs.LocIdKsWrapper(...
    {'learned_models/IdentityKS/mc3_fc3_models_dataset_1/alarm.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/baby.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/femaleSpeech.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/fire.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/crash.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/dog.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/engine.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/footsteps.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/knock.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/maleSpeech.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/femaleScreammaleScream.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/piano.model.mat',...
     'learned_models/IdentityKS/mc3_fc3_models_dataset_1/phone.model.mat'},...
    useCaffe ...
    ); % uses 0.5s blocksize
% block creator
pipe.blockCreator = BlockCreators.MeanStandardBlockCreator( 0.5, 0.5/2 );
% feature creator
pipe.featureCreator = FeatureCreators.FeatureSetNSrcDetectionPlusModelOutputs2();
% label creator
pipe.labelCreator = LabelCreators.NumberOfSourcesLabeler( 'srcMinEnergy', -22 );
% model creator GLMNET regression
pipe.modelCreator = ModelTrainers.GlmNetLambdaSelectTrainer( ...
    'performanceMeasure', @PerformanceMeasures.NSE, ...
    'family', 'poisson', ...
    'cvFolds', 3, ...
    'alpha', 0.99, ...
    'maxDataSize', 2000 );
% pipe.modelCreator = ModelTrainers.SVMmodelSelectTrainer( ...
%     'performanceMeasure', @PerformanceMeasures.MultinomialBAC, ...
%     'hpsEpsilons', [0.001], ...     % define hps set (not a range)
%     'hpsKernels', [2], ...          % 0 = linear, 2 = rbf (not a range)
%     'hpsCrange', [-6 2], ...        % define hps C range -- logspaced between 10^a and 10^b
%     'hpsGammaRange', [-12 3], ...   % define hps Gamma range -- logspaced between 10^a and 
%                               ...   % 10^b. Ignored for kernel other than rbf
%     'hpsMaxDataSize', 1000, ...     % max data set size to use in hps (number of samples)
%     'hpsRefineStages', 8, ...       % number of iterative hps refinement stages
%     'hpsSearchBudget', 24, ...       % number of hps grid search parameter values per dimension
%     'hpsCvFolds', 5,...             % number of hps cv folds of training set
%     'finalMaxDataSize',10000);
pipe.modelCreator.verbose( 'on' );
% train set only for training
pipe.trainset = 'learned_models/IdentityKS/trainTestSets/NIGENS160807_mini_TrainSet_1.flist';
% pipe.trainset = 'mini30_train.flist';
% setup data
pipe.setupData();

%% scene creation

sc(1) = SceneConfig.SceneConfiguration();
sc(1).addSource( SceneConfig.PointSource( ...
        'data', SceneConfig.FileListValGen( 'pipeInput' ),...
        'azimuth', SceneConfig.ValGen( 'manual', 0 ) ) );
sc(1).addSource( SceneConfig.PointSource(...
        'azimuth',SceneConfig.ValGen( 'manual', 45 ),...
        'data', SceneConfig.FileListValGen( pipe.pipeline.trainSet(:,'fileName') ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
        'loop', 'randomSeq' );
sc(1).addSource( SceneConfig.PointSource(...
        'azimuth',SceneConfig.ValGen( 'manual', -45 ),...
        'data', SceneConfig.FileListValGen( pipe.pipeline.trainSet(:,'fileName') ),...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
        'loop', 'randomSeq' );
sc(1).addSource( SceneConfig.DiffuseSource(...
        'offset', SceneConfig.ValGen( 'manual', 0 ) ),...
        'loop', 'randomSeq',...
        'snr', SceneConfig.ValGen( 'manual', -1 ),...
        'snrRef', 1 );
pipe.init( sc, 'fs', 16000 );

%% save model

savePath = pipe.pipeline.run(...
    'modelName', [modelName '-train'],...
    'modelPath', modelPath);

fprintf( ' -- Model is saved at %s -- \n\n', savePath );

%% EOF
