function trainAndTestNumberSources()

startTwoEars('tt_general.config.xml');

%% training & testing
% pipeline creation
pipe = TwoEarsIdTrainPipe( 'cacheSystemDir', [getMFilePath() '/../../idPipeCache'] );
pipe.blockCreator = BlockCreators.MeanStandardBlockCreator( 0.5, 0.2 );
pipe.featureCreator = FeatureCreators.FeatureSet1Blockmean();
% label will be number of active sources
noSrcsLabeler = LabelCreators.NumberOfSourcesLabeler();
pipe.labelCreator = noSrcsLabeler;
pipe.modelCreator = ModelTrainers.GlmNetLambdaSelectTrainer( ...
    'performanceMeasure', @PerformanceMeasures.MultinomialBAC, ...
    'family', 'multinomial', ... % deal with NumberOfSources as a multiclass label
    'cvFolds', 'preFolded', ...  % most reasonable if supplying prefolded dataset definitions
    'maxDataSize', 6000, ...
    'hpsMaxDataSize', 4000, ...
    'alpha', 0.99 );  % prevents numeric instabilities (compared to 1)
pipe.modelCreator.verbose( 'on' );
ModelTrainers.CVtrainer.useParallelComputing( true );

% data setup
pipe.setTrainset( {'DCASE13_mini_TrainSet_f1.flist',...
                   'DCASE13_mini_TrainSet_f2.flist',...
                   'DCASE13_mini_TrainSet_f3.flist',...
                   'DCASE13_mini_TrainSet_f4.flist'} );
pipe.setTestset( {'DCASE13_mini_TestSet.flist'} );
pipe.setupData();

% scene setup
sc = SceneConfig.SceneConfiguration();
sc.addSource( SceneConfig.PointSource( ...
                  'data', SceneConfig.FileListValGen( 'pipeInput' ) ) );
sc.addSource( SceneConfig.PointSource( ...
                  'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ) ),...
              'loop', 'randomSeq',...
              'snr', SceneConfig.ValGen( 'manual', 0 ),...
              'snrRef', 1 );
sc.addSource( SceneConfig.PointSource( ...
                  'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ),...
                  'offset', SceneConfig.ValGen( 'manual', 20 ) ),...
              'loop', 'randomSeq',...
              'snr', SceneConfig.ValGen( 'manual', 0 ),...
              'snrRef', 1 );
sc.addSource( SceneConfig.PointSource( ...
                  'data', SceneConfig.MultiFileListValGen( pipe.srcDataSpec ),...
                  'offset', SceneConfig.ValGen( 'manual', 40 ) ),...
              'loop', 'randomSeq',...
              'snr', SceneConfig.ValGen( 'manual', 0 ),...
              'snrRef', 1 );
sc.setLengthRef( 'source', 1, 'min', 60 );
pipe.init( sc, 'fs', 16000 );

% pipeline run
[modelPath,model,testPerf] = pipe.pipeline.run( 'modelName', 'nsrcs', 'modelPath', 'test_nsrcs_training' );
fprintf( ' -- Model is saved at %s -- \n\n', modelPath );

% short analysis
fprintf( 'Confusion matrix (rows ~ true type, columns ~ predicted type):\nLabels:' );
disp( testPerf.cmLabels' );
disp( testPerf.confusionMatrix );
fprintf( '\n' );

fDescription = pipe.featureCreator.description;
[~,fImpacts] = model.getBestLambdaCVresults();
plotDetailFsProfile( fDescription, fImpacts, '', false );


