function test_glmnet_PDs()
    
addpath( '../..' );
startIdentificationTraining();

featureCreators = {?featureCreators.FeatureSet1Blockmean,...
                   ?featureCreators.FeatureSet1Blockmean2Ch};
azimuths = {{0,0},...
    {0,45},{45,0},{22.5,-22.5},{67.5,112.5},{-157.5,157.5},...
    {0,90},{22.5,112.5},{45,135},{90,180},{22.5,-67.5},{45,-45},{90,0},{-157.5,112.5},...
    {0,180},{22.5,-157.5},{45,-135},{67.5,-112.5},{90,-90}}; % 19 cfgs
snrs = {0,-10,10,-20};
datasets = {'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TrainSet_1.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TestSet_1.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TrainSet_2.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TestSet_2.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TrainSet_3.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TestSet_3.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TrainSet_4.flist',...
            'learned_models/IdentityKS/trainTestSets/NIGENS_75pTrain_TestSet_4.flist'
            };
classes = {'alarm','baby','femaleSpeech','fire','crash','dog','engine','footsteps',...
           'knock','phone','piano'};
       
if exist( 'pds_glmnet_test.mat', 'file' )
    load( 'pds_glmnet_test.mat' );
else
    doneCfgsTest = {};
end

for ddt = [2 4 6]
for cc = 1 : numel( classes )
for ff = 1 : numel( featureCreators )
for ss = 1 : numel( snrs )
for aa = 1 : numel( azimuths )

dd = ddt-1;
aat = aa;
sst = ss;
% TODO: cross tests

fprintf( '\n\n==============\nTesting %s, dd = %d, ff = %d\nss = %d, sst = %d, aa = %d, aat = %d.==============\n\n', ...
    classes{cc}, ddt, ff, ss, sst, aa, aat );

if exist( ['pds_' strrep(num2str(aa),' ','_') '_glmnet.mat'], 'file' )
    load( ['pds_' strrep(num2str(aa),' ','_') '_glmnet'] );
else
    warning( 'training mat file not found' );
    pause;
    continue;
end

if ~any( cellfun( @(x)(all(x==[cc dd ss ff aa])), doneCfgs ) )
    continue; % training not done yet
end
if any( cellfun( @(x)(all(x==[cc ddt ss ff aa sst aat])), doneCfgsTest ) )
    continue; % testing already done
end
    
pipe = TwoEarsIdTrainPipe();
pipe.featureCreator = feval( featureCreators{ff}.Name );
pipe.modelCreator = ...
    modelTrainers.LoadModelNoopTrainer( ...
        @(cn)(fullfile( modelpathes{cc,dd,ss,ff,aa}, [cn '.model.mat'] )), ...
        'performanceMeasure', @performanceMeasures.BAC2, ...
        'modelParams', struct('lambda', []) );
pipe.modelCreator.verbose( 'on' );

pipe.trainset = [];
pipe.testset = datasets{ddt};
pipe.setupData();

sc = sceneConfig.SceneConfiguration();
sc.addSource( sceneConfig.PointSource( ...
    'azimuth',sceneConfig.ValGen('manual',azimuths{aa}{1}) ) );
sc.addSource( sceneConfig.PointSource( ...
    'azimuth',sceneConfig.ValGen('manual',azimuths{aa}{2}), ...
    'data',sceneConfig.FileListValGen(pipe.pipeline.data('general',:,'wavFileName')),...
    'offset', sceneConfig.ValGen('manual',0.0) ),...
    sceneConfig.ValGen( 'manual', snrs{ss} ),...
    true ); % loop
pipe.setSceneConfig( sc );

pipe.init();
modelpathes_test{cc,ddt,ss,ff,aa,sst,aat} = pipe.pipeline.run( {classname}, 0 );

testmodel = load( [modelpathes_test{cc,ddt,ss,ff,aa,sst,aat} filesep classname '.model.mat'] );

test_performances{cc,ddt,ss,ff,aa,sst,aat} = [testmodel.testPerfresults.performance];
cv_performances{cc,ddt,ss,ff,aa,sst,aat} = testmodel.model.lPerfsMean;
cv_std{cc,ddt,ss,ff,aa,sst,aat} = testmodel.model.lPerfsStd;
[coefIdxs_b{cc,ddt,ss,ff,aa,sst,aat},...
 impacts_b{cc,ddt,ss,ff,aa,sst,aat},...
 perf_b{cc,ddt,ss,ff,aa,sst,aat},...
 lambda_b{cc,ddt,ss,ff,aa,sst,aat},...
 nCoefs_b{cc,ddt,ss,ff,aa,sst,aat}] = testmodel.model.getBestLambdaCVresults();
[coefIdxs_bms{cc,ddt,ss,ff,aa,sst,aat},...
 impacts_bms{cc,ddt,ss,ff,aa,sst,aat},...
 perf_bms{cc,ddt,ss,ff,aa,sst,aat},...
 lambda_bms{cc,ddt,ss,ff,aa,sst,aat},...
 nCoefs_bms{cc,ddt,ss,ff,aa,sst,aat}] = testmodel.model.getBestMinStdCVresults();
[coefIdxs_hws{cc,ddt,ss,ff,aa,sst,aat},...
 impacts_hws{cc,ddt,ss,ff,aa,sst,aat},...
 perf_hws{cc,ddt,ss,ff,aa,sst,aat},...
 lambda_hws{cc,ddt,ss,ff,aa,sst,aat},...
 nCoefs_hws{cc,ddt,ss,ff,aa,sst,aat}] = testmodel.model.getHighestLambdaWithinStdCVresults();
lbIdx = find( testmodel.model.model.lambda == lambda_b{cc,ddt,ss,ff,aa,sst,aat} );
lhwsIdx = find( testmodel.model.model.lambda == lambda_hws{cc,ddt,ss,ff,aa,sst,aat} );
test_performances_b{cc,ddt,ss,ff,aa,sst,aat} = test_performances{cc,ddt,ss,ff,aa,sst,aat}(lbIdx);
test_performances_hws{cc,ddt,ss,ff,aa,sst,aat} = test_performances{cc,ddt,ss,ff,aa,sst,aat}(lhwsIdx);
[lambdas{cc,ddt,ss,ff,aa,sst,aat},...
 nCoefs{cc,ddt,ss,ff,aa,sst,aat}] = testmodel.model.getLambdasAndNCoefs();
testTime{cc,ddt,ss,ff,aa,sst,aat} = testmodel.trainTime;
trainTime{cc,ddt,ss,ff,aa,sst,aat} = ...
    load( [modelpathes{cc,dd,ss,ff,aa} filesep classname '.model.mat'], 'trainTime' );

doneCfgsTest{end+1} = [cc ddt ss ff aa sst aat];

save( 'pds_glmnet_test.mat', ...
    'modelpathes_test', 'doneCfgsTest', ...
    'test_performances', 'cv_performances', 'cv_std',...
    'coefIdxs_b', 'impacts_b', 'perf_b', 'lambda_b', 'nCoefs_b',...
    'coefIdxs_bms', 'impacts_bms', 'perf_bms', 'lambda_bms', 'nCoefs_bms',...
    'coefIdxs_hws', 'impacts_hws', 'perf_hws', 'lambda_hws', 'nCoefs_hws',...
    'test_performances_b', 'test_performances_hws', 'lambdas', 'nCoefs', ...
    'trainTime', 'testTime' );

end
end
end
end
end

