function idtestRandomGeneralPointOverlay( classname, testFlist, modelPath )

testpipe = TwoEarsIdTrainPipe();
m = load( fullfile( modelPath, [classname '.model.mat'] ) );
testpipe.featureCreator = m.featureCreator;
testpipe.modelCreator = ...
    modelTrainers.LoadModelNoopTrainer( ...
        @(cn)(fullfile( modelPath, [cn '.model.mat'] )), ...
        'performanceMeasure', @performanceMeasures.BAC2 ...
        );
testpipe.modelCreator.verbose( 'on' );

testpipe.testset = testFlist;

sc = sceneConfig.SceneConfiguration();
sc.angleSignal = sceneConfig.ValGen('random', [0,359.9]);
sc.distSignal = sceneConfig.ValGen('random', [0.5,3]);
sc.addOverlay( ...
    sceneConfig.ValGen('random', [0,359.9]), ...
    sceneConfig.ValGen('random', [0.5,3]),...
    sceneConfig.ValGen('set', [0, 10, 20, 30, 40]), 'point',...
    sceneConfig.ValGen('set', testpipe.pipeline.data('general',:,'wavFileName')), ...
    sceneConfig.ValGen('random', [0, 2]) );
testpipe.setSceneConfig( [sc] ); 

testpipe.init();
testpipe.pipeline.run( {classname}, 0 );

end
