function plotDetailFsProfile_blLen( featureNames, impacts, addTitle )

baseGrpsBlLen = {{'ratemap','blLen 0.2'},{'onsetStrength','blLen 0.2'},...
                 {'amsFeatures','blLen 0.2'},{'spectralFeatures','blLen 0.2'},...
                 {'ratemap','blLen 0.5'},{'onsetStrength','blLen 0.5'},...
                 {'amsFeatures','blLen 0.5'},{'spectralFeatures','blLen 0.5'},...
                 {'ratemap','blLen 1'},{'onsetStrength','blLen 1'},...
                 {'amsFeatures','blLen 1'},{'spectralFeatures','blLen 1'}};
fs = [];
nTotal = 0;
for ii = 1 : numel( baseGrpsBlLen )
    grpIdxs = getFeatureIdxs( featureNames, baseGrpsBlLen{ii} );
    grpImpact(ii) = sum( impacts(grpIdxs) );
    nTotal = nTotal + sum( impacts(grpIdxs) > 0 );
end
fig = figure('Name',['Feature Profile blLen' addTitle],'defaulttextfontsize', 12, ...
       'position', [0, 0, 400,400]);
hold all;
hPlot = bar( [grpImpact(1),grpImpact(2),grpImpact(3),grpImpact(4);...
              grpImpact(5),grpImpact(6),grpImpact(7),grpImpact(8);...
              grpImpact(9),grpImpact(10),grpImpact(11),grpImpact(12)], ...
    'EdgeColor', 'none',...
    'BarWidth', 0.9,...
    'BarLayout', 'stacked' );
set( gca, 'xtick', [1,2,3],'xticklabel', {'0.2s','0.5s','1.0s'} );
set( gca, 'FontSize', 12, 'YGrid', 'on' );
xlabel( 'block length' );
ylabel( 'impact' );
ylim( gca, [0 0.9] );
% xlim( gca, [1.85 4.1] );
rotateXLabels( gca, 60 );
legend( {'ratemap', 'onsetStrength', 'amsFeatures', 'spectralFeatures'}, 'Location', 'Best' );
