function nrs = nanRescStruct()

sdef = {'classIdx',nan,...
        'nAct',nan,...
        'curSnr',nan,...
        'curSnr_db',nan,...
        'curSnr2',nan,...
        'dist2bisector',nan,...
        'azmErr',nan,...
        'azmErr2',nan,...
        'nStream',nan,...
        'nAct_segStream',nan,...
        'curNrj',nan, ...
        'curNrj_db',nan, ...
        'curNrjOthers',nan, ...
        'curNrjOthers_db',nan, ...
        'scpId', nan,...
        'scpIdExt', nan,...
        'fileId', nan,...
        'fileClassId', nan,...
        'blockClass', nan,...
        'gtAzm',nan,...
        'estAzm',nan,...
        'posPresent',nan,...
        'posSnr',nan,...
       };
nrs = struct( sdef{:} );

end
